name: image_scroll_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  http: ^1.2.1
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  fluttertoast: ^8.2.5
  url_launcher: ^6.3.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  open_file: ^3.3.2
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

assets:
  - google_fonts/

flutter:

  uses-material-design: true
